import { Language } from "./types";

export const translations = {
  [Language.EN]: {
    title: "Image Resizer & Code Generator",
    description: "As an expert in image processing, my task is to resize an image to specific dimensions. I will provide you with simple and effective Python code using the Pillow library to accomplish this.",
    uploadImage: "Upload Image",
    orDrop: "or drop an image",
    width: "Width (px)",
    height: "Height (px)",
    resize: "Resize Image",
    download: "Download Resized Image",
    pythonCode: "Python Code (Pillow)",
    copy: "Copy",
    copied: "Copied!",
    original: "Original Image",
    resized: "Resized Image",
    noImage: "No image uploaded",
    noResizedImage: "Resized image will appear here",
    errorNoImage: "Please upload an image first.",
    errorInvalidDims: "Please enter valid width and height.",
    language: "Language",
    english: "English",
    arabic: "العربية",
    removeBackground: "Remove Background",
    removing: "Removing...",
    useNewImage: "Use New Image",
    errorRemoveBg: "Failed to remove background. Please try again.",
    enhanceQuality: "Enhance Quality",
    enhancing: "Enhancing...",
    errorEnhance: "Failed to enhance image. Please try again.",
  },
  [Language.AR]: {
    title: "تغيير وتعديل الصور",
    description: "بصفتي خبيرًا في معالجة الصور، مهمتي هي تعديل حجم صورة معينة إلى أبعاد محددة. سأقدم لك كود بايثون بسيطًا وفعالًا باستخدام مكتبة Pillow لتنفيذ هذه المهمة.",
    uploadImage: "رفع صورة",
    orDrop: "أو اسحب صورة هنا",
    width: "العرض (بكسل)",
    height: "الارتفاع (بكسل)",
    resize: "تغيير الحجم",
    download: "تحميل الصورة المعدلة",
    pythonCode: "كود بايثون (Pillow)",
    copy: "نسخ",
    copied: "تم النسخ!",
    original: "الصورة الأصلية",
    resized: "الصورة المعدلة",
    noImage: "لم يتم رفع أي صورة",
    noResizedImage: "ستظهر الصورة المعدلة هنا",
    errorNoImage: "يرجى رفع صورة أولاً.",
    errorInvalidDims: "يرجى إدخال عرض وارتفاع صالحين.",
    language: "اللغة",
    english: "English",
    arabic: "العربية",
    removeBackground: "إزالة الخلفية",
    removing: "جارٍ الإزالة...",
    useNewImage: "استخدام صورة جديدة",
    errorRemoveBg: "فشل في إزالة الخلفية. يرجى المحاولة مرة أخرى.",
    enhanceQuality: "تحسين الجودة",
    enhancing: "جارٍ التحسين...",
    errorEnhance: "فشل في تحسين الصورة. يرجى المحاولة مرة أخرى.",
  }
};