import { Language } from "./types";

export const translations = {
  [Language.EN]: {
    title: "Image Resizer & Editor",
    description: "Upload an image to resize it, remove the background, or enhance its quality.",
    uploadImage: "Upload Image",
    orDrop: "or drop an image",
    width: "Width (px)",
    height: "Height (px)",
    resize: "Resize Image",
    download: "Download Modified Image",
    original: "Original Image",
    resized: "Modified Image",
    noImage: "No image uploaded",
    noResizedImage: "Modified image will appear here",
    errorNoImage: "Please upload an image first.",
    errorInvalidDims: "Please enter valid width and height.",
    language: "Language",
    english: "English",
    arabic: "العربية",
    removeBackground: "Remove Background",
    removing: "Removing...",
    useNewImage: "Use New Image",
    errorRemoveBg: "Failed to remove background. Please try again.",
    enhanceQuality: "Enhance Quality",
    enhancing: "Enhancing...",
    errorEnhance: "Failed to enhance image. Please try again.",
    // FIX: Add missing translation keys for Python code block
    pythonCode: "Python Code",
    copy: "Copy",
    copied: "Copied!",
  },
  [Language.AR]: {
    title: "تغيير وتعديل الصور",
    description: "ارفع صورة لتغيير حجمها، إزالة الخلفية، أو تحسين جودتها.",
    uploadImage: "رفع صورة",
    orDrop: "أو اسحب صورة هنا",
    width: "العرض (بكسل)",
    height: "الارتفاع (بكسل)",
    resize: "تغيير الحجم",
    download: "تحميل الصورة المعدلة",
    original: "الصورة الأصلية",
    resized: "الصورة المعدلة",
    noImage: "لم يتم رفع أي صورة",
    noResizedImage: "ستظهر الصورة المعدلة هنا",
    errorNoImage: "يرجى رفع صورة أولاً.",
    errorInvalidDims: "يرجى إدخال عرض وارتفاع صالحين.",
    language: "اللغة",
    english: "English",
    arabic: "العربية",
    removeBackground: "إزالة الخلفية",
    removing: "جارٍ الإزالة...",
    useNewImage: "استخدام صورة جديدة",
    errorRemoveBg: "فشل في إزالة الخلفية. يرجى المحاولة مرة أخرى.",
    enhanceQuality: "تحسين الجودة",
    enhancing: "جارٍ التحسين...",
    errorEnhance: "فشل في تحسين الصورة. يرجى المحاولة مرة أخرى.",
    // FIX: Add missing translation keys for Python code block
    pythonCode: "كود بايثون",
    copy: "نسخ",
    copied: "تم النسخ!",
  }
};