// src/constants.ts
export enum Language {
  AR = 'ar',
  EN = 'en',
}

export const translations = {
  [Language.AR]: {
    original: 'الصورة الأصلية',
    resized: 'الصورة المعدلة',
    uploadImage: 'رفع صورة',
    orDrop: 'أو اسحب صورة هنا',
    useNewImage: 'استخدام صورة جديدة',
    width: 'العرض (بكسل)',
    height: 'الارتفاع (بكسل)',
    resize: 'تغيير الحجم',
    removeBackground: 'إزالة الخلفية',
    enhanceQuality: 'تحسين الجودة',
    enhancing: 'جاري التحسين...',
    removing: 'جاري إزالة الخلفية...',
    download: 'تحميل الصورة المعدلة',
    noResizedImage: 'ستظهر الصورة المعدلة هنا',
    errorNoImage: 'الرجاء اختيار صورة أولاً.',
    errorInvalidDims: 'أبعاد غير صالحة.',
    errorRemoveBg: 'فشل في إزالة الخلفية. جرّب صورة أوضح لِشخص.',
    errorEnhance: 'فشل في تحسين الصورة.',
  },
  [Language.EN]: {
    original: 'Original Image',
    resized: 'Edited Image',
    uploadImage: 'Upload image',
    orDrop: 'or drag & drop',
    useNewImage: 'Use a new image',
    width: 'Width (px)',
    height: 'Height (px)',
    resize: 'Resize',
    removeBackground: 'Remove Background',
    enhanceQuality: 'Enhance Quality',
    enhancing: 'Enhancing...',
    removing: 'Removing background...',
    download: 'Download Edited Image',
    noResizedImage: 'Edited image will appear here',
    errorNoImage: 'Please select an image first.',
    errorInvalidDims: 'Invalid dimensions.',
    errorRemoveBg: 'Background removal failed. Try a clearer image of a person.',
    errorEnhance: 'Enhancement failed.',
  },
};
